name: agconnect_clouddb_example
description: Demonstrates how to use the agconnect_clouddb plugin.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.0
  agconnect_auth: 1.2.0+300
  agconnect_clouddb: ^1.3.0+300

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
