// This file has been autogenerated from a class added in the UI designer.

using System;
using AGCAuthXamariniOSDemo.Views;
using Foundation;
using Huawei.Agconnect.Auth;
using UIKit;

namespace AGCAuthXamariniOSDemo
{
    public partial class InfoViewController : UIViewController
    {
        private string name;
        private string id;
        private AGCUser currentUser;

        public InfoViewController(string name, string userIdentifier) : base("InfoVC", null)
        {
            this.name = name;
            this.id = userIdentifier;
        }


        public InfoViewController(IntPtr handle) : base(handle)
        {

        }
        public InfoViewController(AGCUser currentUser)
        {
            this.currentUser = currentUser;
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            Title = "User Info";
            txtName.Text = name;
            txtId.Text = id;
            userImage.Image = UIImage.LoadFromData(currentUser?.PhotoUrl ?? "");
            // Perform any additional setup after loading the view, typically from a nib.
        }

        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);
            // Get the currently logged-in user
            var user = AGCAuth.GetInstance().CurrentUser;
            RefreshView(user);
        }


        private void RefreshView(AGCUser user)
        {
            txtName.Text = user?.DisplayName;
            txtId.Text = user?.Uid;
            if (currentUser?.PhotoUrl != null)
                using (var data = NSData.FromUrl(new NSUrl(currentUser.PhotoUrl)))
                    userImage.Image = UIImage.LoadFromData(data ?? "");
        }

        partial void SignOut_Clicked(NSObject sender)
        {
            AGCAuth.GetInstance().SignOut();
            Console.WriteLine("sign out");
            this.NavigationController.PopViewController(true);
        }

        partial void UserSettings_Clicked(NSObject sender)
        {
            var viewController = new SettingsViewController();
            PresentViewController(viewController, true, null);

        }

        partial void LnkAccount_Clicked(NSObject sender)
        {
            var viewController = new LinkViewController();
            PresentViewController(viewController, true, null);
        }

        partial void DeleteUser_Clicked(NSObject sender)
        {
            AGCAuth.GetInstance().DeleteUser();
            Console.WriteLine("user deleted");
            this.DismissModalViewController(true);
        }

        public override void DidReceiveMemoryWarning()
        {
            base.DidReceiveMemoryWarning();
            // Release any cached data, images, etc that aren't in use.
        }
    }
}
