name: agconnect_appmessaging_example
description: Demonstrates how to use the agconnect_applinking plugin.
version: 1.2.0+221

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  agconnect_appmessaging:
    path: ../

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true