# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AGConnectFunctionDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AGConnectFunctionDemo
  pod 'AGConnectFunction'

  target 'AGConnectFunctionDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AGConnectFunctionDemoUITests' do
    # Pods for testing
  end

end
