# Uncomment the next line to define a global platform for your project

install! 'cocoapods', generate_multiple_pod_projects: true

platform :ios, '9.0'

target 'CloudDBDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'AGConnectAuth'
  pod 'AGConnectDatabase'
  
end
