# Uncomment the next line to define a global platform for your project

install! 'cocoapods', generate_multiple_pod_projects: true

platform :ios, '8.0'

AGCFrameworkVersion = '~> 1.1.0.300'

target 'CloudDBDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'OpenSSL-for-agc-clouddb', '~> 1.1.1g'
  pod 'Protobuf-C++', '~> 3.11.3'
  pod 'SQLCipher', '~> 4.2.0'
  pod 'AGConnectDatabase'
  
  pod 'HMFoundation', AGCFrameworkVersion
  pod 'AGConnectCore', AGCFrameworkVersion
  pod 'AGConnectCredential', AGCFrameworkVersion
  pod 'AGConnectAuth', AGCFrameworkVersion
end
