# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source "https://git.huawei.com/application_market_business/AppGalleryConnectSDK/AM_AppGallery_AppGalleryConnectSDK_ios_spec.git"

target 'AGConnectAppMessagingDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "AGConnectAppMessaging"
  pod "HiAnalytics"
  # Pods for AGConnectAppMessagingDemo

end
