/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.agc.clouddb.quickstart.model;

import com.huawei.agconnect.server.clouddb.request.CloudDBZoneObject;
import com.huawei.agconnect.server.clouddb.annotations.DefaultValue;
import com.huawei.agconnect.server.clouddb.request.Text;
import com.huawei.agconnect.server.clouddb.annotations.NotNull;
import com.huawei.agconnect.server.clouddb.annotations.Indexes;
import com.huawei.agconnect.server.clouddb.annotations.PrimaryKeys;
import com.huawei.agconnect.server.clouddb.annotations.EntireEncrypted;

import com.alibaba.fastjson.annotation.JSONField;

import java.util.Date;

/**
 * Definition of ObjectType BookInfo.
 *
 * @since 2020-12-25
 */
@PrimaryKeys({"id"})
@Indexes({"queryIndex:bookName,price,id", "bookName:bookName"})
public final class BookInfo extends CloudDBZoneObject {
    private Integer id;

    private String bookName;

    private String author;

    private Double price;

    private String publisher;

    private Date publishTime;

    public BookInfo() {
        super(BookInfo.class);

    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    public String getBookName() {
        return bookName;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getAuthor() {
        return author;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Double getPrice() {
        return price;
    }

    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public String getPublisher() {
        return publisher;
    }

    @JSONField(format="yyyy-MM-dd HH:mm:ss SSS")
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    @JSONField(format="yyyy-MM-dd HH:mm:ss SSS")
    public Date getPublishTime() {
        return publishTime;
    }

}
