# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AGConnectStorageDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "AGConnectStorage"
  pod "AGConnectAuth"

end

target 'AGConnectStorageDemo-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "AGConnectStorage"
  pod "AGConnectAuth"

end
