/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class BookInfo {
    getFieldTypeMap() {
        let fieldTypeMap = new Map();
        fieldTypeMap.set('id', 'Integer');
        fieldTypeMap.set('bookName', 'String');
        fieldTypeMap.set('author', 'String');
        fieldTypeMap.set('price', 'Double');
        fieldTypeMap.set('publisher', 'String');
        fieldTypeMap.set('publishTime', 'Date');
        return fieldTypeMap;
    }

    getClassName() {
        return 'BookInfo';
    }

    getPrimaryKeyList() {
        let primaryKeyList = [];
        primaryKeyList.push('id');
        return primaryKeyList;
    }

    getIndexList() {
        let indexList = [];
        indexList.push('bookName,price,id');
        indexList.push('bookName');
        return indexList;
    }

    getEncryptedFieldList() {
        let encryptedFieldList = [];
        return encryptedFieldList;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setBookName(bookName) {
        this.bookName = bookName;
    }

    getBookName() {
        return this.bookName;
    }

    setAuthor(author) {
        this.author = author;
    }

    getAuthor() {
        return this.author;
    }

    setPrice(price) {
        this.price = price;
    }

    getPrice() {
        return this.price;
    }

    setPublisher(publisher) {
        this.publisher = publisher;
    }

    getPublisher() {
        return this.publisher;
    }

    setPublishTime(publishTime) {
        this.publishTime = publishTime;
    }

    getPublishTime() {
        return this.publishTime;
    }
}

module.exports = {BookInfo}