/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

#import "AGCCloudDBObjectTypeInfoHelper.h"
#import "BookInfo.h"

