/*
* Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
* Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
*/

#import <AGConnectDatabase/AGConnectDatabase.h>

NS_ASSUME_NONNULL_BEGIN

@interface BookInfo : AGCCloudDBObject
@property (nonatomic, strong) NSNumber<AGCInt> *id;
@property (nonatomic, copy) NSString *bookName;
@property (nonatomic, copy) NSString *author;
@property (nonatomic, strong) NSNumber<AGCDouble> *price;
@property (nonatomic, copy) NSString *publisher;
@property (nonatomic, strong) NSDate *publishTime;
@property (nonatomic, strong) NSNumber<AGCBool> *shadowFlag;
@end

NS_ASSUME_NONNULL_END