name: agconnect_apm_example
description: Demonstrates how to use the agconnect_apm plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.3
  http: 0.13.3
  agconnect_apm: 1.4.0+200

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
